PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
DESCRIBE «resource-uri» ?resource
WHERE {
	«resource-uri»
	# the object's type
	crm:P2_has_type | 
	# the collection's identifiers/names and their types
	crm:P1_is_identified_by | 
	crm:P1_is_identified_by/crm:P2_has_type 
	?resource
}