PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT
	DISTINCT ?resource
	(MAX(?date) AS ?lastUpdated)
	(1 AS ?sourceCount) # collection descriptions are drawn from a single source: the EMu "accessionlots" file
WHERE {
	?resource a crm:E78_Collection .
	?resource crm:P70i_is_documented_in / dcterms:modified ?date

	FILTER(isuri(?resource)) # ignoring places which have no URI
	# for debugging, filter here:
	# filter (?resource in (<http://nma-dev.conaltuohy.com/xproc-z/collection/3952#>, <http://nma-dev.conaltuohy.com/xproc-z/collection/5300#> ))
}
GROUP BY ?resource
