PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
select distinct ?resource
where {
	?resource a crm:E78_Collection 
	filter(isuri(?resource)) # ignoring places which have no URI
	# for debugging, filter here:
	# filter (?resource in (<http://nma-dev.conaltuohy.com/xproc-z/collection/3952#>, <http://nma-dev.conaltuohy.com/xproc-z/collection/5300#> ))
}
