<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<!-- A mapping from NMA's "additionalType" field to Trove categories -->
	<xsl:template name="category-from-additionalType">
		<xsl:param name="additionalType" select="."/>
		<xsl:choose>
			<xsl:when test="$additionalType = (
				'Theses'
			)">Research &amp; Reports</xsl:when>
			<xsl:when test="$additionalType = (
				'Audio cassettes',
				'Audio records',
				'Audio tapes',
				'Cinematographic film',
				'Compact discs',
				'Movie film',
				'Music books',
				'Music programs',
				'Music rolls',
				'Mutoscope reels',
				'Phonographs',
				'Piano rolls',
				'Reel-to-reel audio tapes',
				'Scores',
				'Sheet music',
				'Sheet Music'
			)">Music, Audio &amp; Video</xsl:when>
			<xsl:when test="$additionalType = (
				'Account books',
				'Account records',
				'Address books',
				'Administrative files',
				'Administrative records',
				'Aerograms',
				'Agricultural records',
				'Aircraft logbooks',
				'Annual reports',
				'Architectural specifications',
				'Autograph books',
				'Aviation documents',
				'Ballot papers',
				'Bankbooks',
				'Birth certificates',
				'Birthday cards',
				'Bus tickets',
				'Business accounts',
				'Business cards',
				'Business letters',
				'Business Letters',
				'Business records',
				'Business stationery',
				'Calculation tables',
				'Calendars',
				'Carbon copies',
				'Cards',
				'Cartes-de-visite',
				'Catalogues',
				'Certificates',
				'Certificates of appreciation',
				'Chequebooks',
				'Cheques',
				'Christmas cards',
				'Commemorative cards',
				'Commemorative envelopes',
				'Contracts',
				'Correspondence',
				'Cricket scoresheets',
				'Dance programs',
				'Deeds',
				'Diaries',
				'Documents',
				'Envelopes',
				'Ephemera',
				'Exercise books',
				'Exhibition catalogues',
				'Financial records',
				'Financial transaction cards',
				'Genealogical documents',
				'Gold licences',
				'Government records',
				'Greeting cards',
				'Health and medical charts',
				'Invitations',
				'Invoices',
				'Itineraries',
				'Lecture notes',
				'Ledgers',
				'Legal documents',
				'Letter books',
				'Lettercards',
				'Letters',
				'Letters of administration',
				'Licences',
				'Lists',
				'Logbooks',
				'Lyric sheets',
				'Manuscripts',
				'Maritime documents',
				'Marriage certificates',
				'Media kits',
				'Medical records',
				'Membership badges',
				'Membership cards',
				'Membership certificates',
				'Memorandums',
				'Menus',
				'Minute books',
				'Mourning cards',
				'Mourning stationery',
				'Notebooks',
				'Notes',
				'Obituaries',
				'Order books',
				'Passports',
				'Patents',
				'Personal letters',
				'Personal papers',
				'Petitions',
				'Placards',
				'Prescription books',
				'Press clippings',
				'Press releases',
				'Price lists',
				'Prize certificates',
				'Promotional material',
				'QSL cards',
				'Ration cards',
				'Receipts',
				'Registers',
				'Reports',
				'Sales catalogues',
				'Sales records',
				'Scorecards',
				'Scoresheets',
				'Scrapbooks',
				'Sport tickets',
				'Sports ephemera',
				'Stationery',
				'Technical notes',
				'Telegrams',
				'Testamurs',
				'Theatre programs',
				'Theatre tickets',
				'Trade certificates',
				'Transport passes',
				'Transport tickets',
				'Travel documents',
				'Visas',
				'Visiting cards',
				'Visitors books',
				'Wages books',
				'Wedding invitations',
				'Writing paper',
				'Albums'
			)">Diaries, Letters &amp; Archives</xsl:when>	
			<xsl:when test="$additionalType = (	
				'Bibles',
				'Biographies',
				'Booklets',
				'Books',
				'Cookbooks',
				'Directories',
				'Instruction booklets',
				'Instruction books',
				'Instruction leaflets',
				'Instructional documents',
				'Journal articles',
				'Journals',
				'Magazines',
				'Maintenance manuals',
				'Manuals',
				'Medical books',
				'Operating manuals',
				'Pamphlets',
				'Pop-up books',
				'Prayer books',
				'Reference books',
				'Religious books',
				'School magazines',
				'Storybooks',
				'Street directories',
				'Technical manuals',
				'Textbooks',
				'Travel books'	
			)">Books &amp; Libraries</xsl:when>
			<xsl:otherwise>Images, Maps &amp; Artefacts</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
